### ISSUE TITLE
[CredentialsError]: Missing credentials in configのエラーが発生してCIが失敗する

### ISSUE THREAD

**Issue by masaya-fukazawa** [reg-viz/reg-suit#564]
## Describe the bug
前提
Github Actionsを使用しています。
reg-publish-s3-pluginを使用しています。

事象
`reg-suit run` コマンド使用時に、Credentialsが読み込めない旨のエラーが発生し、CIが失敗します。
ymlには以下の設定をして実行しています。
```
- name: run reg-suit
  run: |
    yarn reg-suit run -v
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

regconfig.jsonには以下の設定をしています。
```
{
  "core": {
    "workingDir": ".reg",
    "actualDir": "__screenshots__",
    "thresholdRate": 0,
    "ximgdiff": {
      "invocationType": "client"
    }
  },
  "plugins": {
    "reg-keygen-git-hash-plugin": true,
    "reg-notify-github-plugin": {
      "prComment": true,
      "prCommentBehavior": "default",
      "clientId": "my-clientId"
    },
    "reg-publish-s3-plugin": {
      "bucketName": "my-s3-document-name",
      "acl": "private"
    }
  }
}
```

## Expected behavior
`reg-suit run` が成功すること
 
## Actual behavior
`reg-suit run` が失敗

## Screenshots

![Screen Shot 2022-01-14 at 11 25 21](https://user-images.githubusercontent.com/40969762/149441093-d157de5d-ab96-4950-bdf3-b011c41fa7b5.png)
