### ISSUE TITLE
About the example workflow to avoid detached head in github actions

### ISSUE THREAD

**Issue by mamaredo** [reg-viz/reg-suit#590]
Thanks for the great tool : )

## Describe the bug

- I don't think the git pull described in the github actions example in this [Workaround for Detached HEAD - reg-viz/reg-suit readme](https://github.com/reg-viz/reg-suit#workaround-for-detached-head) is necessary.

### Why

```yml
# .github/workflows/reg.yml

- uses: actions/checkout@v2
  with:
    fetch-depth: 0
...

- name: workaround for detached HEAD
  run: |
    git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
```
If you specify 0 for fetch-depth in actions/checkout@v2, you can get all history.
Therefore, a git pull of the detached HEAD workaround is not necessary.

## Reproduced step

Fix `reg-suit/README.md`

```yml
# .github/workflows/reg.yml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm install, build, and test
        run: |
          npm i
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
      - name: run reg-suit
        run: |
          npx reg-suit run
```

<br>

**Comment by t-Asai** [comment]
In my case, `workaround for detached HEAD` is also not necessary as doing below.
```
...
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
...
```

**Comment by yshrsmz** [comment]
I still need the workaround, but a slightly different

```yaml
- name: workaround for detached HEAD
  if: ${{ github.event_name == 'pull_request' }}
  run: |
    git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull
```

with pull_request trigger, I need to use `GITHUB_HEADE_REF` instead of `GITHUB_REF`
